# Generated by Django 5.2.7 on 2025-11-07 04:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
